import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.goto("http://localhost:3000/zh", { extraHTTPHeaders: { "Accept-Language": "zh-CN" } });
await page.getByPlaceholder(/说话内容会出现在这里/).fill("亲爱的朋友:\n见字如面。点预览,直接分享到社交媒体。");
await page.waitForTimeout(1200);
await page.getByRole("button", { name: "预览" }).click();
await page.waitForTimeout(2500);
await page.screenshot({ path: "/tmp/vth-preview-modal.png" });
const hasImg = await page.locator(".fixed img[alt='page 1']").count();
console.log("modal 图片:", hasImg);
console.log("分享按钮:", await page.locator(".fixed button", { hasText: "X" }).count() > 0 ? "X ✓" : "?", await page.locator("button:has-text('WhatsApp')").count() > 0 ? "WhatsApp ✓" : "?", await page.locator("button:has-text('复制图片')").count() > 0 ? "复制 ✓" : "?");
await browser.close();
