import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
const logs = [];
page.on("pageerror", (e) => logs.push("PAGEERROR: " + e.message.slice(0, 500)));
page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") logs.push(m.type().toUpperCase() + ": " + m.text().slice(0, 500)); });
await page.goto("http://localhost:3000/", { extraHTTPHeaders: { "Accept-Language": "zh-CN" } });
await page.locator("input[type=file]").setInputFiles("/tmp/vth-tts.wav");
await page.waitForTimeout(20000);
console.log(logs.slice(0, 12).join("\n---\n") || "(no logs)");
await browser.close();
