import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
const errors = [];
page.on("pageerror", (e) => errors.push("PAGEERROR: " + e.message.slice(0, 200)));
await page.goto("http://localhost:3000/", { extraHTTPHeaders: { "Accept-Language": "zh-CN" } });
await page.getByPlaceholder(/说话内容会出现在这里/).fill("计划;h\njhl'\nytt'vhvkkhk\n");
await page.waitForTimeout(1500);
const text = await page.locator(".paper").first().innerText();
console.log("paper innerText:", JSON.stringify(text));
const idx = await page.locator(".paper [data-idx]").evaluateAll(els => els.map(e => e.dataset.idx + ":" + e.textContent).join(" "));
console.log("spans:", idx);
console.log(errors.join("\n") || "no page errors");
await browser.close();
