import type { CursiveLetterPage } from "./cursiveLetters";

/** 第一批难字母之外的 40 课。cursiveLetters.ts 会把两批按 a–z、A–Z 排好。 */

function lesson(spec: {
  letter: string;
  form: "lowercase" | "capital";
  title: string;
  description: string;
  h1: string;
  intro: string;
  steps: [string, string, string];
  mistakes: [string, string, string];
  words: [string, string, string, string, string];
  faqs: [[string, string], [string, string], [string, string]];
}): CursiveLetterPage {
  return {
    slug: spec.form === "lowercase" ? spec.letter : `capital-${spec.letter.toLowerCase()}`,
    letter: spec.letter,
    name: spec.letter,
    form: spec.form,
    meta: { en: { title: spec.title, description: spec.description } },
    copy: {
      en: {
        h1: spec.h1,
        intro: spec.intro,
        steps: [...spec.steps],
        mistakes: [...spec.mistakes],
        words: [...spec.words],
        faqs: spec.faqs.map(([q, a]) => ({ q, a })),
      },
    },
  };
}

export const CURSIVE_LETTER_REST: CursiveLetterPage[] = [
  lesson({
    letter: "a",
    form: "lowercase",
    title: "How to Write a Cursive A (Lowercase): Strokes + Practice Sheet",
    description: "The cursive a is a closed oval with a short exit. Learn the roll-over stroke, the mistakes that leave it open, and print a practice sheet.",
    h1: "How to write a cursive a",
    intro: "Lowercase a is the oval family: the same opening as c, d, g, o, and q. Close the oval or the letter reads as a u. The sample is an open-source cursive font; your hand will round it differently.",
    steps: [
      "Start the cursive a on the baseline. Swing up to the midline, then roll left and around into a small oval.",
      "Close the oval where the stroke meets itself near the midline. An open gap here is what turns a into a u.",
      "Pull a short downstroke to the baseline and exit to the right, ready to join the next letter.",
    ],
    mistakes: [
      "Leaving the oval open. If you can see daylight on the right side, the a collapses into a u the moment you speed up.",
      "Starting at the top, like a print a. Cursive a enters from the baseline so it can connect from the letter before it.",
      "A huge oval that crashes into the headline. The bowl of a lives between the baseline and the midline, not up in l territory.",
    ],
    words: ["apple", "and", "cat", "rain", "happy"],
    faqs: [
      ["Does a cursive a connect on both sides?", "Yes. The entry comes up from the previous letter, and the short exit on the baseline runs into the next one. That is why a feels easy inside a word and awkward when you write it alone."],
      ["Why does my cursive a look like a u?", "The oval never closed. Slow down at the top of the bowl and make the stroke touch itself before you drop to the baseline. A closed a stays an a even when the ink is light."],
      ["Is the cursive a the same stroke as o?", "They share the roll-over opening. o stops as a closed circle; a adds the short downstroke and the exit. Practice a and o on the same line so the shared start becomes automatic."],
    ],
  }),
  lesson({
    letter: "b",
    form: "lowercase",
    title: "How to Write a Cursive B (Lowercase): Strokes + Practice Sheet",
    description: "Cursive b is a tall loop plus a bump that closes on the baseline. Strokes, the b-versus-h mix-up, and a free practice sheet.",
    h1: "How to write a cursive b",
    intro: "Lowercase b climbs to the headline, loops, and finishes with a closed bump like a backwards oval. Mix up the bump and you have written h. The sample font is a model, not the only legal shape.",
    steps: [
      "Start the cursive b on the baseline and rise all the way to the headline, leaning slightly right.",
      "Loop over to the left and pull straight down to the baseline. The loop should be narrow, not a balloon.",
      "From the baseline, bump out to the right, around, and back to the line, then exit right to join the next letter.",
    ],
    mistakes: [
      "An open bump. If the right side never returns to the baseline, b turns into h. Close the bump before you exit.",
      "A short ascender. b must reach the headline. Stop at the midline and it reads as a strange a.",
      "A wide loop that collides with the bump. Keep the loop skinny so the bump has room to close.",
    ],
    words: ["baby", "ball", "blue", "rabbit", "about"],
    faqs: [
      ["How do you tell cursive b from cursive h?", "b closes a bump on the baseline, like a belly. h makes an open arch, like n, and never comes back to seal the right side. If you can trace a circle on the right of the stem, it is a b."],
      ["Does cursive b connect to the next letter?", "Yes. The bump finishes on the baseline with a small exit stroke. Letters before b also connect in, which is why b is easier in the middle of a word than at the start."],
      ["Where should the loop of b sit?", "The loop belongs in the upper half, between the midline and the headline. A loop that sags down to the midline makes the letter look top-heavy and crowds the bump."],
    ],
  }),
  lesson({
    letter: "c",
    form: "lowercase",
    title: "How to Write a Cursive C (Lowercase): Strokes + Practice Sheet",
    description: "Cursive c is an open curve, not a closed o. Learn where it starts, why it often does not exit, and print a practice sheet.",
    h1: "How to write a cursive c",
    intro: "Lowercase c is the open cousin of a and o. It swings up, curves over, and stops. Close it and you have written o. Most school styles do not give c a baseline exit.",
    steps: [
      "Start the cursive c on the baseline and swing up to just above the midline.",
      "Roll left and down in an open curve. Stop on the right side, a little above the baseline, without closing the shape.",
      "Lift. The next letter begins its own entry stroke. Do not drag a line out of the bottom of the c.",
    ],
    mistakes: [
      "Closing the curve into an o. Leave a clear gap on the right, about the width of a pencil line.",
      "Starting too low, so the c sits like a comma. The top of the curve should touch the midline.",
      "Adding a long exit along the baseline. That tail is what a and d have. c stays open and short.",
    ],
    words: ["cat", "come", "circle", "face", "school"],
    faqs: [
      ["Does a cursive c connect to the next letter?", "Usually no. The letter after c starts with its own upstroke, which visually tucks against the open side. Forcing an exit from the bottom of c makes it look like a badly closed a."],
      ["Why does my c look like an e?", "e adds a small loop inside the curve. c is a single open stroke with no inner loop. If you see a closed eye in the middle, you have written e."],
      ["How big should a cursive c be?", "It lives between the baseline and the midline, the same band as a, o, and e. A c that reaches the headline is an accidental capital."],
    ],
  }),
  lesson({
    letter: "d",
    form: "lowercase",
    title: "How to Write a Cursive D (Lowercase): Strokes + Practice Sheet",
    description: "Cursive d starts like a, then the last stroke climbs to the headline and comes back down. Strokes, height mistakes, and a practice sheet.",
    h1: "How to write a cursive d",
    intro: "Lowercase d is an a with a tall finish. Build the oval first, then send the stroke up to the headline and straight back down. A short stick is the usual failure.",
    steps: [
      "Start the cursive d on the baseline and form the same closed oval you use for a, sitting on the midline.",
      "Instead of a short exit, rise from the right side of the oval all the way to the headline.",
      "Pull straight down to the baseline, slightly right of the oval, and add a small exit stroke to the right.",
    ],
    mistakes: [
      "Stopping the ascender at the midline. Then d is just a tall a, and readers hesitate.",
      "Putting the tall stroke on the left, like a print d. In this cursive the stick is the last stroke, on the right.",
      "A leaning stick that misses the oval. The downstroke should kiss the right side of the bowl so the letter stays one piece.",
    ],
    words: ["dog", "red", "door", "friend", "and"],
    faqs: [
      ["Is cursive d the same as cursive a?", "Only the opening. a ends with a short downstroke. d spends that last stroke going up to the headline and back down, which is why d takes longer than it looks."],
      ["Does cursive d connect?", "Yes, on the way out. The final downstroke lands on the baseline and exits right. The letter before d connects into the oval the same way it connects into a."],
      ["Why do people confuse d and cl?", "If the oval and the stick separate, d breaks into a c plus an l. Keep the stick touching the oval, and do not lift the pen between them."],
    ],
  }),
  lesson({
    letter: "e",
    form: "lowercase",
    title: "How to Write a Cursive E (Lowercase): Strokes + Practice Sheet",
    description: "Cursive e is a small loop on the midline, not a print e. Learn the loop size, the open-e mistake, and print a practice sheet.",
    h1: "How to write a cursive e",
    intro: "Lowercase e is one of the first letters worth drilling, because the little loop shows up inside other letters later. Keep it small. A big loop becomes an l.",
    steps: [
      "Start the cursive e on the baseline and swing up toward the midline in a shallow curve.",
      "Just under the midline, loop left into a small eye, then around so the stroke crosses itself.",
      "Exit to the right along the midline. The loop should be no taller than the letter a.",
    ],
    mistakes: [
      "A loop the size of l. If the eye reaches the headline, you have left the e family.",
      "An open curve with no eye. That is a c. The stroke has to cross itself.",
      "Sitting the whole letter on the baseline with no entry. e needs the swing up so it can join from the letter before.",
    ],
    words: ["see", "the", "letter", "tree", "every"],
    faqs: [
      ["Where does the cursive e sit on the lines?", "The loop lives on the midline. The entry starts on the baseline, but the letter itself should not fill the whole space up to the headline."],
      ["Does cursive e connect?", "Yes. The exit runs along the midline into the next letter, which is higher than the exit of a or i. That high join is why see feels smooth and the feels slightly different."],
      ["How is cursive e different from cursive l?", "Same idea, different address. l loops between the headline and the baseline. e loops in the small band under the midline. Drill a row of e then a row of l so the heights separate."],
    ],
  }),
  lesson({
    letter: "h",
    form: "lowercase",
    title: "How to Write a Cursive H (Lowercase): Strokes + Practice Sheet",
    description: "Cursive h is a tall loop plus an open arch, not a closed b. Strokes, the h-versus-b test, and a free practice sheet.",
    h1: "How to write a cursive h",
    intro: "Lowercase h borrows the tall loop of l and the arch of n. The arch stays open. Close it and the letter becomes b, which is the mistake this page is here to prevent.",
    steps: [
      "Start the cursive h on the baseline and climb to the headline, then loop left and come straight down.",
      "At the baseline, swing up and over into one arch, the same hump you use for n, peaking at the midline.",
      "Bring the arch down to the baseline and exit right. Do not curve back into the stem.",
    ],
    mistakes: [
      "Closing the arch so it touches the stem. That sealed shape is b, not h.",
      "A pointy arch, like a printed h. The hump should be round and the same height as n.",
      "A loop so wide it eats the arch. Keep the ascender narrow and give the hump its own space.",
    ],
    words: ["the", "hand", "chair", "house", "school"],
    faqs: [
      ["What is the one difference between cursive h and b?", "The right side. h is an open arch that ends on the baseline and leaves. b swings back and closes a bump against the stem. Check the right side before you check the height."],
      ["Does cursive h connect?", "Yes, out of the arch, along the baseline. The tall loop is only the start. Students who stop after the loop have written l."],
      ["How tall is the arch of h?", "Midline, same as n and m. The loop is the only part that reaches the headline. An arch that climbs to the headline makes the letter look like a double l."],
    ],
  }),
  lesson({
    letter: "i",
    form: "lowercase",
    title: "How to Write a Cursive I (Lowercase): Strokes + Practice Sheet",
    description: "Cursive i is a short retrace plus a dot. Learn the entry, the exit, and where the dot belongs, then print a practice sheet.",
    h1: "How to write a cursive i",
    intro: "Lowercase i looks like a stick and is not one. You swing up, retrace down, and exit, then dot. Skip the exit and the next letter has nothing to hold.",
    steps: [
      "Start the cursive i on the baseline and swing up to the midline.",
      "Retrace down to the baseline and exit a short stroke to the right before you lift.",
      "Dot above the midline, directly over the letter, after the word or at least after the exit.",
    ],
    mistakes: [
      "Dotting before the exit, so the dot becomes a blob on the join.",
      "No entry swing. A naked vertical line does not connect from the previous letter.",
      "A dot floating halfway to the next word. Keep it over the stem, not over the exit.",
    ],
    words: ["it", "is", "little", "find", "time"],
    faqs: [
      ["When do you dot a cursive i?", "After the letter is formed, usually when you finish the word. Dotting mid-letter makes you lift too soon and lose the exit stroke that joins i to whatever follows."],
      ["Does cursive i connect on both sides?", "Yes. The swing up receives the previous letter, and the short baseline exit feeds the next one. The dot is the only part that does not connect."],
      ["How is cursive i different from cursive e?", "i is a straight retrace with a dot. e is a loop with no dot. If your i has a closed eye, you are mixing the two."],
    ],
  }),
  lesson({
    letter: "k",
    form: "lowercase",
    title: "How to Write a Cursive K (Lowercase): Strokes + Practice Sheet",
    description: "Cursive k is a tall loop plus a small kick that touches the stem. Strokes, the k-versus-h mix-up, and a practice sheet.",
    h1: "How to write a cursive k",
    intro: "Lowercase k starts like h and then refuses the open arch. A small in-and-out kick touches the stem around the midline. Miss the touch and k falls apart into h.",
    steps: [
      "Start the cursive k on the baseline, rise to the headline, loop left, and come straight down to the baseline.",
      "Swing a short stroke back up along the stem to about the midline, so the pen is touching the downstroke.",
      "Kick out to the right and slightly down, ending on the baseline with a small exit. The kick is one curve, not a second letter.",
    ],
    mistakes: [
      "An open arch that never touches the stem. That is h. The kick has to meet the stem before it leaves.",
      "A kick that starts at the headline. It belongs near the midline, not up in the loop.",
      "Two separate sticks with a gap. k is one continuous idea: loop, touch, kick.",
    ],
    words: ["like", "make", "kitten", "book", "sky"],
    faqs: [
      ["Why is cursive k harder than h?", "h is one familiar arch. k asks you to come back to the stem and leave again on a smaller curve. The extra touch is the whole letter, and it disappears when you rush."],
      ["Does cursive k connect?", "Yes, from the end of the kick along the baseline. The tall loop does not connect upward. Practice kite slowly until the kick lands before you speed up."],
      ["Should the kick of k be closed like a loop?", "In the style this site teaches, it is a small curve that touches and leaves, not a closed oval. A fully closed kick starts to look like a cursive b glued to an l."],
    ],
  }),
  lesson({
    letter: "l",
    form: "lowercase",
    title: "How to Write a Cursive L (Lowercase): Strokes + Practice Sheet",
    description: "Cursive l is a single tall loop from baseline to headline and back. Learn the width, the height, and print a practice sheet.",
    h1: "How to write a cursive l",
    intro: "Lowercase l is the plain tall loop. No hump, no crossbar, no dot. If you can keep it narrow and full height, b, h, k, and f all get easier, because they begin the same way.",
    steps: [
      "Start the cursive l on the baseline and rise to the headline, leaning a little right.",
      "Loop over to the left at the top. Keep the loop narrow, about the width of the letter i.",
      "Pull straight down to the baseline and exit right. Do not add a hump.",
    ],
    mistakes: [
      "A loop as wide as an oval. Wide loops crash into the next letter and look like a capital.",
      "Stopping at the midline. l that short is an i without a dot, or a stretched e.",
      "Adding a hump at the bottom. That extra arch is the start of h or b, not part of l.",
    ],
    words: ["little", "look", "ball", "play", "yellow"],
    faqs: [
      ["Does cursive l connect?", "Yes. It enters from the baseline and exits along the baseline. A row of l looks like a fence because each exit feeds the next climb."],
      ["How is cursive l different from cursive e?", "Height. e loops under the midline. l loops at the headline and travels the full distance back to the baseline. Same motion, different address on the lines."],
      ["Should I lift the pen on l?", "No. One stroke: up, over, down, exit. A lift at the top usually means the loop is being drawn as two sticks, which is print, not cursive."],
    ],
  }),
  lesson({
    letter: "m",
    form: "lowercase",
    title: "How to Write a Cursive M (Lowercase): Strokes + Practice Sheet",
    description: "Cursive m is three even arches, not a printed zigzag. Strokes, the uneven-hump problem, and a free practice sheet.",
    h1: "How to write a cursive m",
    intro: "Lowercase m is n with one more arch. The work is keeping three humps the same height and the same width. The third hump is the one that usually shrinks.",
    steps: [
      "Start the cursive m on the baseline and swing up and over the first arch, peaking at the midline.",
      "Come down to the baseline and repeat a second arch, the same height and width as the first.",
      "Add the third arch, come down to the baseline, and exit right. Count the humps if you lose the rhythm.",
    ],
    mistakes: [
      "A shrunken last arch. All three peaks should touch the same midline.",
      "Pointy peaks, like a printed m. Each arch is round, the same curve you use for n.",
      "Starting at the top of the first arch with no entry. The swing up from the baseline is what connects m to the letter before it.",
    ],
    words: ["me", "my", "come", "home", "summer"],
    faqs: [
      ["How many strokes is a cursive m?", "One, if you count lifts. Three arches in a single traveling stroke. Students who lift between arches lose the joins and start drawing a print m."],
      ["How do you keep the arches even?", "Say over, down, over, down, over, down as you write, and aim every peak at the midline. The verbal count stops the last arch from collapsing."],
      ["Does cursive m connect?", "Yes, in and out along the baseline. It does not connect from the top. That is why m feels heavy in the middle of a word and fine once the rhythm is there."],
    ],
  }),
  lesson({
    letter: "n",
    form: "lowercase",
    title: "How to Write a Cursive N (Lowercase): Strokes + Practice Sheet",
    description: "Cursive n is two arches: an entry and one hump. Learn the roundness, the n-versus-m count, and print a practice sheet.",
    h1: "How to write a cursive n",
    intro: "Lowercase n is the single arch that m repeats. Two hills, not three. Point the hill and it starts to look like a printed n or a hasty r.",
    steps: [
      "Start the cursive n on the baseline and swing up to the midline for the entry arch.",
      "Come down, then swing up and over a second arch, the same height, peaking at the midline.",
      "Bring that arch down to the baseline and exit right. Stop. A third arch would make it m.",
    ],
    mistakes: [
      "Adding a third hump. Count: entry, one arch, exit. Three peaks means you wrote m.",
      "A sharp peak. The top of n is round. A point belongs to r, and only as a small hook.",
      "Arches of different heights. Both peaks sit on the midline, not one on the headline.",
    ],
    words: ["and", "in", "not", "one", "friend"],
    faqs: [
      ["What is the difference between cursive n and m?", "One arch versus two, after the shared entry. If you are unsure, count the peaks before you lift the pen. n has two, m has three."],
      ["Does cursive n connect?", "Yes, along the baseline on both sides. The letter is a traveling wave, which is why in and and feel smooth once the arch is round."],
      ["Why does my n look like h?", "h has a loop that reaches the headline before the arch. n never goes above the midline. If you climbed to the top line, you started an h."],
    ],
  }),
  lesson({
    letter: "o",
    form: "lowercase",
    title: "How to Write a Cursive O (Lowercase): Strokes + Practice Sheet",
    description: "Cursive o is a closed oval that retraces out to the right. Strokes, the open-o mistake, and a free practice sheet.",
    h1: "How to write a cursive o",
    intro: "Lowercase o shares its opening with a, but it does not drop a stick. You close the oval and retrace a short way out to the right so the next letter can join.",
    steps: [
      "Start the cursive o on the baseline and swing up to the midline, rolling left into an oval.",
      "Close the oval completely. The end of the stroke should meet the start near the top right.",
      "Retrace slightly and exit to the right at the midline. Do not drop to the baseline the way a does.",
    ],
    mistakes: [
      "An open oval. A gap turns o into c, or into a when you add a tail by habit.",
      "Exiting from the bottom. The join from o leaves near the midline, not along the baseline.",
      "A skinny oval that looks like a loop of e. Give o a real bowl, as wide as it is tall.",
    ],
    words: ["to", "you", "look", "one", "school"],
    faqs: [
      ["Does cursive o connect?", "Yes, but the exit is high, near the midline, after a short retrace. That high join is the detail people skip, and then the next letter starts in the wrong place."],
      ["How is cursive o different from a?", "a closes the oval and then pulls down to the baseline. o closes the oval and leaves sideways. Practice them as a pair: same opening, different ending."],
      ["Should I lift the pen inside o?", "No. Close it and retrace out in the same stroke. A lift usually means the oval was drawn like a print o, clockwise from the top, which will not join."],
    ],
  }),
  lesson({
    letter: "p",
    form: "lowercase",
    title: "How to Write a Cursive P (Lowercase): Strokes + Practice Sheet",
    description: "Cursive p drops below the baseline, then adds a short arch. Strokes, the short-descender mistake, and a practice sheet.",
    h1: "How to write a cursive p",
    intro: "Lowercase p is a descender with a small arch, not a printed stick and bowl. The tail has to cross the baseline or the letter reads as n. Keep the descender clear of the next letter.",
    steps: [
      "Start the cursive p on the baseline, swing up to the midline, and pull straight down past the baseline into the descender space.",
      "Curve the tail slightly left at the bottom, then come back up to the baseline along the same stem.",
      "Add one short arch to the right, like a small n, peaking at the midline, and exit on the baseline.",
    ],
    mistakes: [
      "A descender that barely crosses the line. p then looks like n with a nervous tail.",
      "A huge loop under the line that crashes into g or y on the next row.",
      "Forgetting the arch, so the letter is only a descending stick.",
    ],
    words: ["play", "up", "help", "jump", "apple"],
    faqs: [
      ["Does cursive p connect?", "Yes, from the little arch on the baseline. The descender itself does not join to the next letter. Write the tail first, then the arch, then the exit."],
      ["How deep should the tail of p go?", "About the same depth as the descender of g, clearly below the baseline, but not so deep that it hits the line underneath. On three-line paper, stop before the next headline."],
      ["How is cursive p different from cursive b?", "b loops above the midline and closes a bump. p dives below the baseline and finishes with an open arch. They are mirrors in height, not the same letter flipped."],
    ],
  }),
  lesson({
    letter: "r",
    form: "lowercase",
    title: "How to Write a Cursive R (Lowercase): Strokes + Practice Sheet",
    description: "Cursive r is a short stroke plus a small roof, not a full arch. Learn the r-versus-n test and print a practice sheet.",
    h1: "How to write a cursive r",
    intro: "Lowercase r is the letter people turn into n. It rises to the midline and ends with a small roof or hook, not a second full arch. Keep the hook shorter than you think.",
    steps: [
      "Start the cursive r on the baseline and swing up to the midline, like the start of i.",
      "Retrace down only a short way, then branch into a small roof that points right.",
      "End the roof near the midline and bring a short exit toward the baseline. Do not draw a second hump.",
    ],
    mistakes: [
      "A full second arch. That is n. The roof of r is a hook, not a hill you could fit an o inside.",
      "A roof that climbs above the midline toward the headline. r stays in the small band.",
      "No retrace, so the letter is a single slanted stick. The little down-then-out is what readers use to see r.",
    ],
    words: ["red", "run", "for", "three", "letter"],
    faqs: [
      ["Why does my cursive r look like n?", "The hook got promoted into a full arch. Stop the roof early, while it is still small, and exit. If the second shape has the same size as the first rise, you wrote n."],
      ["Does cursive r connect?", "Yes. The entry is a normal baseline swing, and the exit leaves from the roof toward the next letter. It connects, it just does not travel as far as n."],
      ["Is there more than one cursive r?", "Yes. Some school books teach a wave r and some a hooked r. This page uses the short roof. Pick one and keep it, because mixing them inside a word is what makes r unreadable."],
    ],
  }),
  lesson({
    letter: "s",
    form: "lowercase",
    title: "How to Write a Cursive S (Lowercase): Strokes + Practice Sheet",
    description: "Cursive s is a small winding stroke that often starts higher than its neighbors. Strokes, size mistakes, and a practice sheet.",
    h1: "How to write a cursive s",
    intro: "Lowercase s does not look like a printed s, and it often begins near the midline rather than with a long baseline entry. Keep it small. A large s becomes a stray capital.",
    steps: [
      "Begin the cursive s near the midline. Curve left and down toward the baseline, like the start of a loose spiral.",
      "Round the bottom on the baseline and swing back up toward the right, closing a small belly.",
      "Finish with a short exit to the right around the midline, so the next letter can join.",
    ],
    mistakes: [
      "Drawing a printed s, with two separate curves and a lift in the middle.",
      "Making it as tall as l. The whole s lives between the baseline and the midline.",
      "A bottom that does not reach the baseline, so the letter floats and will not join.",
    ],
    words: ["see", "said", "is", "school", "this"],
    faqs: [
      ["Does cursive s connect on the left?", "Often weakly. Many writers start s with a small lift or a very short entry, then connect strongly on the way out. Do not force a long lead-in or the letter tips over."],
      ["How is cursive s different from cursive c?", "c is one open curve and stops. s winds down and back up, so it has a belly and an exit. If you only drew the first curve, you stopped at c."],
      ["Why is s hard at the start of a word?", "There is no previous letter to lean on, and the starting point is higher than a or i. Write a row of s alone before you put it in see or said."],
    ],
  }),
  lesson({
    letter: "t",
    form: "lowercase",
    title: "How to Write a Cursive T (Lowercase): Strokes + Practice Sheet",
    description: "Cursive t is a medium-height stroke plus a crossbar. Learn where to cross it so it does not become l, and print a practice sheet.",
    h1: "How to write a cursive t",
    intro: "Lowercase t is taller than i and shorter than l, and it is not finished until you cross it. The cross sits near the midline. Cross at the top and readers see a fancy l.",
    steps: [
      "Start the cursive t on the baseline and rise above the midline, about halfway to the headline. Not all the way up.",
      "Retrace down to the baseline and exit right, the same join you use for i.",
      "Lift and cross with a short horizontal stroke through the stem, right at the midline.",
    ],
    mistakes: [
      "Full l height. t stops between the midline and the headline. If it touches the top line, it is too tall.",
      "Crossing above the letter, in the air. The bar has to cut the stem.",
      "No exit before the cross. The join happens on the baseline; the cross is a second, small stroke.",
    ],
    words: ["the", "to", "it", "little", "letter"],
    faqs: [
      ["When do you cross a cursive t?", "After the stem and the exit, often at the end of the word, the same moment you dot an i. Crossing too early makes the bar slant and miss the stem."],
      ["Does cursive t connect?", "Yes, from the baseline exit. The crossbar does not connect to the next letter. It is a separate stroke, like the dot on i."],
      ["How is cursive t different from l?", "Height and the bar. l reaches the headline and has no cross. t is shorter and is crossed at the midline. A row of t next to a row of l makes the difference obvious."],
    ],
  }),
  lesson({
    letter: "u",
    form: "lowercase",
    title: "How to Write a Cursive U (Lowercase): Strokes + Practice Sheet",
    description: "Cursive u is two valleys that both return to the baseline. Strokes, the u-versus-v ending, and a practice sheet.",
    h1: "How to write a cursive u",
    intro: "Lowercase u is i written twice, without a dot. Both valleys come back to the baseline. If the last stroke stays up in the air, you have started a v.",
    steps: [
      "Start the cursive u on the baseline, swing up to the midline, and retrace down, like an undotted i.",
      "Without lifting, swing up to the midline again and retrace down to the baseline a second time.",
      "Exit to the right along the baseline. Both bottoms should sit on the line.",
    ],
    mistakes: [
      "Ending with an upstroke that never comes down. That finish belongs to v.",
      "Pointy bottoms. u is round at the baseline, like a smile, not a zigzag.",
      "A second valley much smaller than the first. Match the height: both peaks at the midline.",
    ],
    words: ["you", "up", "funny", "blue", "jump"],
    faqs: [
      ["How do you tell cursive u from v?", "Look at the ending. u comes back down to the baseline and exits. v swings up and stays up. The last stroke is the whole difference."],
      ["Does cursive u connect?", "Yes, in and out on the baseline. It is one of the most connecting letters, which is why you and funny feel easy once the two valleys match."],
      ["Should u be dotted?", "No. A dot makes the first valley look like i and the second like a mistake. Save dots for i and j."],
    ],
  }),
  lesson({
    letter: "v",
    form: "lowercase",
    title: "How to Write a Cursive V (Lowercase): Strokes + Practice Sheet",
    description: "Cursive v ends in the air, on an upstroke. Learn that finish, the v-versus-u mistake, and print a practice sheet.",
    h1: "How to write a cursive v",
    intro: "Lowercase v starts like u and then refuses to come back down. The last stroke climbs to the midline and stops. Bring it down and you have written u.",
    steps: [
      "Start the cursive v on the baseline and swing up to the midline, then down into one round valley.",
      "From the bottom of that valley, swing up to the right and stop at the midline.",
      "Lift. Do not retrace down. The next letter starts its own entry under that raised ending.",
    ],
    mistakes: [
      "Coming back to the baseline. That extra downstroke is u. Stop while the pen is still high.",
      "A sharp point at the bottom. The valley should be as round as u.",
      "An ending that shoots above the midline toward the headline. v stays in the small band.",
    ],
    words: ["have", "over", "very", "give", "love"],
    faqs: [
      ["Does cursive v connect to the next letter?", "Indirectly. The letter itself ends high, and the next letter begins with a new entry stroke. There is no baseline exit the way u has. That break is normal."],
      ["Why does v turn into u when I write fast?", "Speed adds the downstroke you use for every other letter. Pause at the top of the last swing until not coming down feels deliberate."],
      ["Is cursive v one stroke?", "Yes. Up, down, up, lift. A printed v of two straight lines will not join from the letter before it."],
    ],
  }),
  lesson({
    letter: "w",
    form: "lowercase",
    title: "How to Write a Cursive W (Lowercase): Strokes + Practice Sheet",
    description: "Cursive w is a u that finishes like v: two valleys, then an upstroke that stays up. Strokes and a practice sheet.",
    h1: "How to write a cursive w",
    intro: "Lowercase w is the long version of u, with the ending of v. Two full valleys return to the baseline, and the last stroke climbs and stops. Four motions, one pen lift at the end.",
    steps: [
      "Start the cursive w on the baseline and write the first valley, up to the midline and back down, like u.",
      "Add a second valley, the same height, also returning to the baseline.",
      "From that second bottom, swing up to the midline and stop. Do not add a third downstroke.",
    ],
    mistakes: [
      "A third valley. That is u with an extra bump, not w. The last motion goes up and stays up.",
      "Uneven valleys, the second one tiny. Both peaks belong on the midline.",
      "Pointy bottoms. Keep them round or w starts to look like a zigzag print letter.",
    ],
    words: ["we", "where", "down", "two", "yellow"],
    faqs: [
      ["How is cursive w different from u?", "u ends on the baseline. w takes one more climb and ends in the air, like v. Count the returns to the line: u returns twice and stops, w returns twice and then leaves upward."],
      ["Does cursive w connect?", "On the way in, yes. On the way out, the next letter starts fresh under the raised ending, same as v. Do not drag a line down from the last peak."],
      ["Why is w so wide?", "It is three climbs. Narrow each valley a little or the letter will crowd the margin. Width is fine; uneven height is the real problem."],
    ],
  }),
  lesson({
    letter: "x",
    form: "lowercase",
    title: "How to Write a Cursive X (Lowercase): Strokes + Practice Sheet",
    description: "Cursive x is a curve plus a separate crossing stroke. Learn where they meet, and print a practice sheet.",
    h1: "How to write a cursive x",
    intro: "Lowercase x is one of the few small letters that lifts the pen. You write a joining curve first, then cross it. Skip the cross and the letter is an unfinished n or a stray c.",
    steps: [
      "Start the cursive x on the baseline and swing up and over a slanted curve down to the baseline, like a narrow arch, with a short exit.",
      "Lift. From the upper left of that curve, pull a second stroke down to the right, crossing near the middle.",
      "Stop the cross on the baseline side. It does not need its own long exit; the first stroke already joined onward.",
    ],
    mistakes: [
      "Crossing up near the midline, so the letter looks like a k.",
      "Two straight print strokes with no entry. The first stroke has to be able to connect.",
      "Forgetting the second stroke entirely. An uncrossed x disappears into the word.",
    ],
    words: ["box", "next", "extra", "six", "fox"],
    faqs: [
      ["Does cursive x connect?", "The first stroke does, in and out along the baseline. The crossing stroke is separate, like the cross on t. Connect with the curve, then cross."],
      ["When do you add the cross?", "Right after the curve, before the next word, the same habit as crossing t. Waiting until the end of a long word is how crosses land on the wrong letter."],
      ["Why does x feel different from the other small letters?", "Because of the pen lift. Most lowercase letters are one traveling stroke. x asks for a second motion, so it is worth a row of its own before you hide it inside next or extra."],
    ],
  }),
  lesson({
    letter: "y",
    form: "lowercase",
    title: "How to Write a Cursive Y (Lowercase): Strokes + Practice Sheet",
    description: "Cursive y is a u whose second stroke drops into a descender loop. Strokes, the open-tail mistake, and a practice sheet.",
    h1: "How to write a cursive y",
    intro: "Lowercase y starts like u and then falls. The second valley does not stop on the baseline; it keeps going, loops under, and climbs back so the next letter can join.",
    steps: [
      "Start the cursive y on the baseline and write one valley, up to the midline and back down, like the first half of u.",
      "Swing up to the midline again, then pull down past the baseline into the descender space.",
      "Loop left and under, come back up to the baseline, and exit right. The loop should close.",
    ],
    mistakes: [
      "Stopping on the baseline. That is u. The second stroke has to descend.",
      "An open tail that never returns to the line, so the next letter cannot join.",
      "A descender so deep it collides with the headline of the row below.",
    ],
    words: ["you", "yellow", "my", "funny", "play"],
    faqs: [
      ["How is cursive y different from g?", "g begins with a closed oval, like a. y begins with a valley, like u. Both loop under the line, but the top half is a different family."],
      ["Does cursive y connect?", "Yes, after the under-loop climbs back to the baseline. If your y ends in a dangling tail, the join is missing and the next letter starts too far right."],
      ["Should the loop of y close?", "Yes, in this style. An open tail is a legal variant in some books, but it is slower to join. Close the loop until the exit is automatic, then decide if you want the open form."],
    ],
  }),
  lesson({
    letter: "A",
    form: "capital",
    title: "How to Write a Cursive Capital A: Strokes + Practice Sheet",
    description: "Cursive capital A is a large leaning oval with a lead-in, not a printed triangle. Strokes, the open-A mistake, and a practice sheet.",
    h1: "How to write a cursive capital A",
    intro: "Capital A in cursive is a closed oval the height of the headline, often with a small entry stroke. It does not look like the printed A of two sticks and a bar. Leave it open and it reads as a capital C.",
    steps: [
      "For capital A, start near the headline and swing left and down, around a large oval that sits on the baseline.",
      "Bring the stroke back up the right side and close the oval near where you began.",
      "Finish with a short exit to the right at the baseline if your style joins capitals; otherwise lift. Keep the oval closed either way.",
    ],
    mistakes: [
      "A printed A: two diagonals and a crossbar. Cursive A has no crossbar. The closure is the oval itself.",
      "An oval that does not reach the headline, so the capital looks like a lowercase a.",
      "Leaving the right side open. Close it or the letter is a capital C with extra ink.",
    ],
    words: ["Apple", "And", "Amy", "Adam", "Anna"],
    faqs: [
      ["Does a cursive capital A connect to the next letter?", "Some styles add a small baseline exit, and some lift. Either is readable. What is not optional is the closed oval. Connect only after the shape is shut."],
      ["How big is cursive capital A?", "From the baseline to the headline, the full height of l and b. A short A gets mistaken for lowercase a in the middle of a name."],
      ["Why does my capital A look like O?", "The entry flourish is missing and the oval is too round and upright. A slight rightward lean, the same slant as the rest of the page, keeps A from turning into O."],
    ],
  }),
  lesson({
    letter: "B",
    form: "capital",
    title: "How to Write a Cursive Capital B: Strokes + Practice Sheet",
    description: "Cursive capital B is a stem plus two stacked curves. Learn the gap between the bowls, and print a practice sheet.",
    h1: "How to write a cursive capital B",
    intro: "Capital B is a downstroke and two bowls, the upper one smaller than the lower. It rarely joins to the next letter. Uneven bowls are the usual tell.",
    steps: [
      "For capital B, pull a slightly curved stem from the headline down to the baseline.",
      "From the top of the stem, swing a small bowl out to the right and back to the stem at the midline.",
      "From that midpoint, swing a larger bowl out and back to the baseline end of the stem. Lift. B does not need an exit stroke.",
    ],
    mistakes: [
      "Two bowls the same size. The lower bowl should be wider, or B looks like a printed block.",
      "A gap so the bowls never touch the stem. Each curve has to come home.",
      "A straight ruler stem. A slight bow to the left is what makes the letter look written.",
    ],
    words: ["Baby", "Blue", "Ball", "Ben", "Beth"],
    faqs: [
      ["Does cursive capital B connect?", "No, in ordinary school styles. The lower bowl ends on the stem. The next letter starts on its own. Forcing a join pulls the bottom bowl open."],
      ["How is capital B different from capital R?", "R's lower half is a leg that leaves the stem and does not close. B's lower half is a bowl that returns. If the bottom stroke comes back, it is B."],
      ["Where does the middle of B sit?", "On the midline, the same line lowercase a and c use. A middle join that sags makes the upper bowl huge and the lower one cramped."],
    ],
  }),
  lesson({
    letter: "C",
    form: "capital",
    title: "How to Write a Cursive Capital C: Strokes + Practice Sheet",
    description: "Cursive capital C is a large open curve with a small entry. Strokes, the closed-C mistake, and a free practice sheet.",
    h1: "How to write a cursive capital C",
    intro: "Capital C is the open oval: almost an A or O, stopped before it closes. A small entry stroke at the top keeps it from looking like a printed C.",
    steps: [
      "For capital C, begin with a short entry near the headline, moving into the top of the curve.",
      "Swing down the left side in a broad curve that reaches the baseline.",
      "Round the bottom and stop on the right, still open. Leave a gap wide enough to see. Do not close it into O.",
    ],
    mistakes: [
      "Closing the right side. Then the letter is O or A. Stop while the gap is obvious.",
      "A tiny c sitting on the midline. Capital C uses the full headline-to-baseline height.",
      "No entry stroke, so the top looks chopped off, like a print C drawn with a ruler.",
    ],
    words: ["Cat", "Come", "Circle", "Carol", "Chris"],
    faqs: [
      ["Does cursive capital C connect?", "No. It is a pen lift, and the next letter starts fresh. An exit tail from the bottom turns C into a malformed capital G or a lowercase a."],
      ["How is capital C different from lowercase c?", "Size and the entry. Lowercase c lives under the midline. Capital C fills the whole line height and usually starts with a small lead-in at the top."],
      ["What slant should C use?", "The same slant as the rest of the page, leaning slightly right. An upright C looks pasted in from a print alphabet."],
    ],
  }),
  lesson({
    letter: "D",
    form: "capital",
    title: "How to Write a Cursive Capital D: Strokes + Practice Sheet",
    description: "Cursive capital D is a tall stem closed by one broad bowl. Strokes, the open-D mistake, and a practice sheet.",
    h1: "How to write a cursive capital D",
    intro: "Capital D is one tall stroke and one bowl, not two bowls like B. The bowl leaves the top and comes home at the baseline. Leave it open and the letter reads as a strange L.",
    steps: [
      "For capital D, pull a stem from the headline to the baseline, with a slight leftward bow.",
      "From the top, swing a single broad curve out to the right, the full height of the stem.",
      "Bring that curve back to the baseline end of the stem so the bowl closes. Lift.",
    ],
    mistakes: [
      "A second, smaller bowl in the middle. That is B. D has one curve.",
      "A bowl that stops in midair and never reaches the stem at the bottom.",
      "A stem that only reaches the midline, so the capital shrinks into a lowercase d.",
    ],
    words: ["Dog", "Door", "Red", "David", "Diana"],
    faqs: [
      ["Does cursive capital D connect?", "Not in the usual school hand. The bowl ends on the stem. Start the next letter separately rather than dragging a line out of the bottom."],
      ["How wide should the bowl be?", "About as wide as the stem is tall, or a little less. A very thin D looks like a closed capital L. A very fat D crowds the next letter."],
      ["How is capital D different from capital O?", "O has no separate stem; it is one oval. D has a clear back edge, the stem, and the curve attaches to it at top and bottom."],
    ],
  }),
  lesson({
    letter: "E",
    form: "capital",
    title: "How to Write a Cursive Capital E: Strokes + Practice Sheet",
    description: "Cursive capital E is a vertical curve with three small arms, or one continuous ribbon. Strokes and a practice sheet.",
    h1: "How to write a cursive capital E",
    intro: "Capital E in cursive is not three horizontal bars on a stick. One flowing stroke makes a small top, a middle, and a larger bottom. Flat printed bars are the mistake.",
    steps: [
      "For capital E, start at the headline with a small curve that moves right, then back left into the stem.",
      "Continue down and swing a smaller middle curve out to the right, around the midline, and back.",
      "Finish with a broader curve along the baseline, ending to the right. The bottom loop is the largest of the three.",
    ],
    mistakes: [
      "Three straight bars, equally long, on a ruler stem. That is print E.",
      "A middle curve as big as the bottom one, so the letter looks like a stack of e.",
      "Stopping after two curves. E needs the baseline finish or it reads as a capital C.",
    ],
    words: ["Every", "See", "Tree", "Emma", "Edward"],
    faqs: [
      ["Does cursive capital E connect?", "The last curve can trail slightly, but most writers lift before the next letter. Do not turn the bottom into a long join; it flattens the letter."],
      ["How many pen lifts does capital E take?", "One stroke is the goal. Lifting for each bar produces the printed form. If one stroke is too much, slow the middle curve rather than breaking the letter apart."],
      ["Why does my E look like a 6?", "The top curve is missing and the bottom loop is too round. Put a clear small curve at the headline first, then the larger base."],
    ],
  }),
  lesson({
    letter: "H",
    form: "capital",
    title: "How to Write a Cursive Capital H: Strokes + Practice Sheet",
    description: "Cursive capital H is two stems joined by a midline curve. Strokes, the missing-bar mistake, and a practice sheet.",
    h1: "How to write a cursive capital H",
    intro: "Capital H is two tall strokes and a joining curve at the midline. It is not a lowercase h made bigger. Both stems reach the headline, and the bridge actually touches them.",
    steps: [
      "For capital H, pull the left stem from the headline down to the baseline, with a slight curve.",
      "Start the right stem at the headline as well. Before you finish it, swing a curve from the left stem across at the midline to meet it.",
      "Bring the right stem down to the baseline. Both feet sit on the line. Lift.",
    ],
    mistakes: [
      "A bridge that misses one of the stems, so the letter is two floating l shapes.",
      "Only one tall stroke plus an arch. That is lowercase h, even if you draw it big.",
      "A bridge up at the headline or down on the baseline. It belongs at the midline.",
    ],
    words: ["Hand", "House", "The", "Hannah", "Henry"],
    faqs: [
      ["Does cursive capital H connect?", "No. Both stems end on the baseline without an exit into the next letter. The bridge is internal. Start the following letter on its own."],
      ["Can I write H in one stroke?", "Some ornamental hands do. The reliable school version is two stems and a bridge, with a lift. Connectedness matters less than both stems being full height."],
      ["How do I stop H looking like K?", "K's right side leaves the stem and does not come back down as a second full stem from the headline. H has two stems that both start at the top."],
    ],
  }),
  lesson({
    letter: "I",
    form: "capital",
    title: "How to Write a Cursive Capital I: Strokes + Practice Sheet",
    description: "Cursive capital I is a small top curve, a stem, and a base, not a dotted stick. Strokes and a practice sheet.",
    h1: "How to write a cursive capital I",
    intro: "Capital I is not a tall lowercase i. It has a small cap at the top and a base at the bottom, and it is not dotted. Dot it and readers think the word started with a lowercase letter.",
    steps: [
      "For capital I, start near the headline with a short curve moving right, then left into the stem.",
      "Pull the stem down to the baseline, slightly curved, the full height of the other capitals.",
      "Finish with a small base curve along the baseline, to the right. Do not add a dot.",
    ],
    mistakes: [
      "A single stick with a dot. That is lowercase i stretched too tall.",
      "No base, so the stem stops abruptly and looks unfinished next to J.",
      "A huge top loop that reaches into the line above. The cap is small.",
    ],
    words: ["It", "Is", "Iris", "India", "I"],
    faqs: [
      ["Does cursive capital I get a dot?", "No. The dot belongs to lowercase i and to j. Capital I is identified by the top and bottom curves. Adding a dot creates a double letter."],
      ["Does capital I connect?", "The base can lead slightly into the next letter in some hands, but a full join is optional. Keep the stem vertical enough to read before you worry about the join."],
      ["How is capital I different from capital J?", "J continues below the baseline and usually hooks left. I stops on the baseline with a small foot. If you crossed the line, you started a J."],
    ],
  }),
  lesson({
    letter: "K",
    form: "capital",
    title: "How to Write a Cursive Capital K: Strokes + Practice Sheet",
    description: "Cursive capital K is a stem plus an arm and a leg that meet the stem. Strokes and a practice sheet.",
    h1: "How to write a cursive capital K",
    intro: "Capital K is a tall stem and two strokes on the right that meet it around the midline. If they miss the stem, K falls into a lowercase k or a loose R.",
    steps: [
      "For capital K, pull a stem from the headline down to the baseline.",
      "From the upper right, swing a short arm down-left so it touches the stem near the midline.",
      "From that touch, kick a longer leg down-right to the baseline. The leg does not curve back into the stem.",
    ],
    mistakes: [
      "Arm and leg that never touch the stem, floating to the right like a separate v.",
      "A closed lower bowl. That return makes the letter B or R, not K.",
      "A stem that stops at the midline, which shrinks K into lowercase k.",
    ],
    words: ["Kitten", "Like", "Book", "Kate", "Kevin"],
    faqs: [
      ["Does cursive capital K connect?", "No. The leg ends on the baseline and lifts. A join from the leg usually pulls it into a loop and the letter starts to look like R."],
      ["Where should the arm meet the stem?", "Near the midline, not up at the headline and not down at the baseline. A high join makes a tiny leg and a letter that looks top-heavy."],
      ["How is capital K different from capital R?", "R closes or curves the top into a bowl and sends the leg out from that bowl. K's top is an arm that hits the stem and bounces away. The touch point is sharper on K."],
    ],
  }),
  lesson({
    letter: "L",
    form: "capital",
    title: "How to Write a Cursive Capital L: Strokes + Practice Sheet",
    description: "Cursive capital L is one tall loop with a base, not a printed right angle. Strokes and a practice sheet.",
    h1: "How to write a cursive capital L",
    intro: "Capital L is a single looping stroke: up near the headline, over, and down into a base on the baseline. A printed L of two straight lines will not match the rest of a cursive page.",
    steps: [
      "For capital L, start on the baseline and rise to the headline, looping left at the top the way lowercase l does, but broader.",
      "Bring the stroke down the right side of that loop, all the way to the baseline.",
      "Sweep the base out to the right along the line and lift. The base is part of the same stroke, not a second pen line.",
    ],
    mistakes: [
      "A small loop that never reaches the headline, so the capital looks like lowercase l.",
      "A base drawn as a separate horizontal bar, disconnected from the stem.",
      "A loop so wide it occupies the space of the next letter.",
    ],
    words: ["Little", "Look", "Play", "Liam", "Lucy"],
    faqs: [
      ["Does cursive capital L connect?", "The base can lead into the next letter more naturally than most capitals. Keep the lead short. A long tail makes the following letter start too low."],
      ["How is capital L different from lowercase l?", "Mostly size and the base. Lowercase l exits with a small joining stroke. Capital L spends more ink on a clear foot so it reads as a capital at the start of a name."],
      ["Can L be written without a loop?", "Some italic hands use a plain stem. The looped form is the one that matches the other capitals on this site. Stay with the loop so L, B, and H share a slant."],
    ],
  }),
  lesson({
    letter: "M",
    form: "capital",
    title: "How to Write a Cursive Capital M: Strokes + Practice Sheet",
    description: "Cursive capital M is a series of arches starting from the baseline, not a printed zigzag. Strokes and a practice sheet.",
    h1: "How to write a cursive capital M",
    intro: "Capital M begins on the baseline, climbs, and makes a pointed or rounded pair of peaks above the midline. It is wider than lowercase m and it usually does not join onward.",
    steps: [
      "For capital M, start on the baseline and swing up to the headline, then down toward the midline.",
      "Climb again to a second peak near the headline, slightly to the right of the first.",
      "Bring the last stroke down to the baseline and stop. Both peaks should match in height.",
    ],
    mistakes: [
      "Three rounded lowercase arches. Capital M is taller and usually starts with a stronger first climb.",
      "A second peak much shorter than the first, so the letter slouches.",
      "An extra joining loop at the end that turns the last stroke into lowercase m.",
    ],
    words: ["Me", "My", "Home", "Mary", "Mark"],
    faqs: [
      ["Does cursive capital M connect?", "Usually no. It ends on the baseline and the next letter starts clean. A small exit is harmless; a full lowercase join makes the capital look unfinished."],
      ["How many peaks does capital M have?", "Two main peaks, after the opening stroke. If you count three equal hills, you have written a large lowercase m."],
      ["Should the peaks be pointed?", "A slight point is normal in many school styles, unlike the round arches of lowercase m. Do not make them so sharp that the letter looks printed."],
    ],
  }),
  lesson({
    letter: "N",
    form: "capital",
    title: "How to Write a Cursive Capital N: Strokes + Practice Sheet",
    description: "Cursive capital N is one tall arch and a final stem, not two lowercase humps. Strokes and a practice sheet.",
    h1: "How to write a cursive capital N",
    intro: "Capital N is a climb, a diagonal or curve down, and a final stem back up to the headline in some styles, or down to the baseline in others. This page uses the form that ends on the baseline, so it sits with M.",
    steps: [
      "For capital N, start on the baseline and rise to the headline in a smooth curve.",
      "Sweep down to the right, arriving at the baseline. That diagonal is the body of the letter.",
      "Finish with a short uptick or a final stem that stops cleanly. Do not add the extra arches of M.",
    ],
    mistakes: [
      "Two round humps, which means you wrote a large lowercase n.",
      "A diagonal so flat the letter looks like a check mark with no height.",
      "A final stroke that climbs all the way back to the headline and then adds another hill. That extra hill is M.",
    ],
    words: ["Not", "And", "One", "Noah", "Nancy"],
    faqs: [
      ["How do I tell capital N from capital M?", "Count the peaks at the headline. N has one main climb. M has two. If you made a second peak as tall as the first, you have crossed into M."],
      ["Does capital N connect?", "No, not as a rule. End it and lift. The lowercase n is the one that travels into the next letter along the baseline."],
      ["Why do N and M feel similar?", "They share the opening climb from the baseline. Practice them as a pair and stop N after the diagonal, before your hand adds M's second peak out of habit."],
    ],
  }),
  lesson({
    letter: "O",
    form: "capital",
    title: "How to Write a Cursive Capital O: Strokes + Practice Sheet",
    description: "Cursive capital O is a full-height closed oval. Strokes, the open-O mistake, and a practice sheet.",
    h1: "How to write a cursive capital O",
    intro: "Capital O is the plain closed oval at full height. No stem, no crossbar. The work is closing it and giving it the same slant as the rest of the page.",
    steps: [
      "For capital O, start near the headline and circle left and down to the baseline.",
      "Round the bottom and come up the right side.",
      "Close the oval at the top. A small overlap is better than a gap. Lift, without a long exit.",
    ],
    mistakes: [
      "A gap on the right, which turns O into capital C.",
      "An oval no taller than lowercase o. Capitals use the headline.",
      "A lead-out that drops to the baseline and starts a lowercase a. Stop when the oval closes.",
    ],
    words: ["One", "Look", "To", "Olivia", "Owen"],
    faqs: [
      ["Does cursive capital O connect?", "No. Close it and lift. An exit stroke is how O turns into Q or into a joined lowercase letter. The next letter starts on its own."],
      ["How is capital O different from capital A?", "A has a clearer entry and a more pointed or leaning close. O is the simpler oval. If you are unsure which you wrote, look for A's lead-in at the top left."],
      ["How is capital O different from Q?", "Q adds a tail that crosses or sits on the baseline. O does not. If there is a stroke outside the oval, it is no longer O."],
    ],
  }),
  lesson({
    letter: "P",
    form: "capital",
    title: "How to Write a Cursive Capital P: Strokes + Practice Sheet",
    description: "Cursive capital P is a stem and one upper bowl, not a descender. Strokes and a practice sheet.",
    h1: "How to write a cursive capital P",
    intro: "Capital P stays above the baseline. A stem and a single bowl in the upper half. Drop a tail under the line and you have mixed it with lowercase p.",
    steps: [
      "For capital P, pull a stem from the headline down to the baseline.",
      "From the top of the stem, swing one bowl out to the right and back to the stem.",
      "Close the bowl at or slightly above the midline. Stop. There is no second bowl and no descender.",
    ],
    mistakes: [
      "A second bowl below the first. That is capital B.",
      "A stem that continues under the baseline. Capital P does not descend.",
      "A bowl that never returns to the stem, so the letter looks like a capital D missing its close, or a loose curve.",
    ],
    words: ["Play", "Help", "Apple", "Paul", "Penny"],
    faqs: [
      ["Does cursive capital P connect?", "No. The bowl ends on the stem. Leave the next letter to start by itself."],
      ["How is capital P different from capital B?", "Count the bowls. P has one, in the top half. B has two, and the lower one is bigger. One extra curve is the whole difference."],
      ["How is capital P different from lowercase p?", "Lowercase p descends below the line and finishes with a small arch. Capital P is tall, closed at the top, and its stem stops on the baseline."],
    ],
  }),
  lesson({
    letter: "R",
    form: "capital",
    title: "How to Write a Cursive Capital R: Strokes + Practice Sheet",
    description: "Cursive capital R is a stem, a bowl, and a leg that leaves. Strokes, the R-versus-B test, and a practice sheet.",
    h1: "How to write a cursive capital R",
    intro: "Capital R begins like P and then sends a leg down to the baseline. Bring that leg back to the stem and you have written B. The leg has to leave.",
    steps: [
      "For capital R, pull a stem from the headline to the baseline.",
      "Add one bowl from the top of the stem back to the stem near the midline, the same bowl as P.",
      "From that meeting point, stroke a leg down-right to the baseline. The leg does not return.",
    ],
    mistakes: [
      "Closing the bottom into a second bowl. That is B. The leg must end in the open.",
      "A leg that starts at the headline instead of at the bowl, so the letter splits into a P plus a slash.",
      "A tiny bowl, so R reads as K. Give the top a real curve before the leg leaves.",
    ],
    words: ["Red", "Run", "Letter", "Rose", "Ryan"],
    faqs: [
      ["Does cursive capital R connect?", "No. The leg ends on the baseline and you lift. Extending it into the next letter flattens the slant that makes R readable."],
      ["How is capital R different from K?", "R's top is a closed or nearly closed bowl attached to the stem. K's top is an arm that meets the stem at an angle and bounces. The top of R is rounder."],
      ["Where should the leg start?", "Where the bowl meets the stem, around the midline. A leg that starts higher leaves a gap, and a leg that starts lower has no bowl left to be an R."],
    ],
  }),
  lesson({
    letter: "U",
    form: "capital",
    title: "How to Write a Cursive Capital U: Strokes + Practice Sheet",
    description: "Cursive capital U is a full-height valley with a small entry. Strokes, the extra-stem mistake, and a practice sheet.",
    h1: "How to write a cursive capital U",
    intro: "Capital U is a deep valley from headline to baseline and back up, often with a short lead-in. It is not lowercase u doubled in size, and it does not grow a descender.",
    steps: [
      "For capital U, start near the headline with a short entry, then sweep down to the baseline in a broad curve.",
      "Round the bottom. Do not point it.",
      "Rise to the headline on the right and finish with a small stroke inward or a clean stop. Both sides should match in height.",
    ],
    mistakes: [
      "A pointed bottom, like a printed V stretched open.",
      "A right side that only reaches the midline, so the letter looks like lowercase u.",
      "A tail under the baseline. That descender belongs to Y, not U.",
    ],
    words: ["You", "Up", "Funny", "Uma", "Under"],
    faqs: [
      ["Does cursive capital U connect?", "Sometimes a slight exit from the top right, more often a lift. Do not drop back to the baseline to force a join; that extra stroke turns U into a different letter."],
      ["How is capital U different from capital V?", "U rounds along the baseline and comes back up. V meets at a point or a sharp curve and the sides are straighter. If you can rest the letter on the line for a moment, it is U."],
      ["How is capital U different from Y?", "Y continues below the line after the valley. U stops when the right side reaches the headline height. Crossing the baseline means you have left U."],
    ],
  }),
  lesson({
    letter: "V",
    form: "capital",
    title: "How to Write a Cursive Capital V: Strokes + Practice Sheet",
    description: "Cursive capital V is two full-height strokes that meet at the baseline. Strokes and a practice sheet.",
    h1: "How to write a cursive capital V",
    intro: "Capital V comes down from the headline to a low point on the baseline and back up. Keep the bottom narrower than capital U. A wide round bottom is how V becomes U.",
    steps: [
      "For capital V, start at the headline and sweep down to the baseline, leaning right.",
      "Meet the baseline in a narrow curve, not a long flat rest.",
      "Rise to the headline on the right and stop. Both arms should reach the same height.",
    ],
    mistakes: [
      "A broad flat bottom that sits on the line. That is U.",
      "One arm much shorter, so the letter leans over and looks unfinished.",
      "Stopping at the midline. Capital V uses the full height.",
    ],
    words: ["Very", "Have", "Over", "Victor", "Vera"],
    faqs: [
      ["Does cursive capital V connect?", "No. It ends high, and the next letter starts on its own. There is no baseline exit."],
      ["How is capital V different from lowercase v?", "Lowercase v lives between the baseline and the midline and joins from a previous letter. Capital V starts at the headline and does not join in from the left."],
      ["Should the bottom be a sharp point?", "A small curve is enough. A needle point is hard to read and hard to repeat. The difference from U is the width of that bottom, not how sharp you can make it."],
    ],
  }),
  lesson({
    letter: "W",
    form: "capital",
    title: "How to Write a Cursive Capital W: Strokes + Practice Sheet",
    description: "Cursive capital W is two valleys at full height. Strokes, the extra-hump mistake, and a practice sheet.",
    h1: "How to write a cursive capital W",
    intro: "Capital W is capital V with one more valley, or capital U that comes to a narrower bottom twice. Four endpoints: start high, down, up, down, up. Keep both bottoms on the baseline.",
    steps: [
      "For capital W, start at the headline and sweep down to the baseline, then back up to the headline.",
      "Without adding a rounded lowercase hump, sweep down to the baseline a second time.",
      "Rise to the headline once more and stop. The two bottoms should be similar, and both sides should match the first peak in height.",
    ],
    mistakes: [
      "Three bottoms. That extra valley is a different letter. W returns to the line twice.",
      "Bottoms so round and wide that each half is a capital U.",
      "A last stroke that only reaches the midline, so the letter looks cut off.",
    ],
    words: ["We", "Where", "Two", "Will", "Wendy"],
    faqs: [
      ["Does cursive capital W connect?", "No. It finishes at the top of the last stroke. The lowercase w is the one that can feel joined, and even that one ends in the air."],
      ["How do I keep W from getting too wide?", "Narrow each valley slightly and keep the slant consistent. Width is allowed; a last stroke that shrinks is the error to fix first."],
      ["How is capital W different from capital M?", "M starts on the baseline and reaches up to peaks. W starts at the headline and reaches down to valleys. Turn the page upside down and they are cousins, which is why people swap them."],
    ],
  }),
  lesson({
    letter: "X",
    form: "capital",
    title: "How to Write a Cursive Capital X: Strokes + Practice Sheet",
    description: "Cursive capital X is two crossing full-height strokes. Learn where they cross, and print a practice sheet.",
    h1: "How to write a cursive capital X",
    intro: "Capital X crosses near the middle of the line height. It is two strokes, and neither of them should be so curved that the letter becomes a fancy Y. The cross is the letter.",
    steps: [
      "For capital X, sweep from the upper left near the headline down to the lower right on the baseline.",
      "Lift. Start the second stroke at the upper right, near the headline.",
      "Cross the first stroke around the midline and finish at the lower left on the baseline. The two strokes should be similar in length.",
    ],
    mistakes: [
      "A cross up at the headline or down on the baseline, so one side is a stub.",
      "Adding a descender. Capital X stays between headline and baseline. A tail means you drifted into Y.",
      "One curved stroke only. X is not finished until the second stroke crosses it.",
    ],
    words: ["Box", "Next", "Extra", "Xavier", "Max"],
    faqs: [
      ["Does cursive capital X connect?", "No. Both strokes end on their own. Pick up the pen for the cross, the same habit as lowercase x, then leave the next letter to start fresh."],
      ["How is capital X different from lowercase x?", "Height. Lowercase x is a small joining curve plus a short cross between the baseline and the midline. Capital X spans the full line and does not join."],
      ["Should the strokes be straight?", "Slightly curved is normal in a cursive hand. Dead-straight strokes look printed. The requirement is that they cross near the center, not that they are ruler-straight."],
    ],
  }),
  lesson({
    letter: "Y",
    form: "capital",
    title: "How to Write a Cursive Capital Y: Strokes + Practice Sheet",
    description: "Cursive capital Y drops below the baseline. Strokes, the no-tail mistake, and a free practice sheet.",
    h1: "How to write a cursive capital Y",
    intro: "Capital Y is a valley like U, then a descender. In many school hands the right stroke continues under the line and hooks left. Without that tail, the letter is just U.",
    steps: [
      "For capital Y, start near the headline and sweep down toward the baseline, as if you were starting U.",
      "Bring a second stroke from the upper right down through the first stroke.",
      "Continue that second stroke below the baseline and finish with a small hook to the left. The tail is part of Y, not decoration.",
    ],
    mistakes: [
      "Stopping on the baseline, which leaves a capital U.",
      "A tail so long it hits the next line of writing.",
      "A hook that swings right and crashes into the next letter. The hook tucks left, under the letter.",
    ],
    words: ["You", "Yellow", "My", "Yves", "Yolanda"],
    faqs: [
      ["Does cursive capital Y connect?", "No. The hook ends under the line. The next letter starts on the baseline, to the right of the tail, not from the hook."],
      ["How is capital Y different from capital U?", "The descender. U finishes above the baseline. Y keeps going and hooks underneath. If your pen never crossed the line, you have not written Y."],
      ["How deep is the tail?", "Similar to lowercase g or y: clearly below the baseline, short of the next row. On wide-ruled paper there is room; on college-ruled paper, keep the hook small."],
    ],
  }),
];
