// 构建期字形分析:为描红笔画引导提取每个拉丁字形的落笔点与初始笔画方向。
// 产物 src/lib/glyphStarts.generated.ts(纯数据,运行时不依赖 opentype.js)。
// 用法:node scripts/glyph-starts.mjs
import fs from "node:fs";
import path from "node:path";
import opentype from "opentype.js";

const root = path.resolve(import.meta.dirname, "..");

const FONTS = [
  { id: "caveat", file: "fonts-src/Caveat[wght].ttf" },
  { id: "patrickhand", file: "fonts-src/PatrickHand-Regular.ttf" },
  { id: "kalam", file: "fonts-src/Kalam-Regular.ttf" },
  { id: "indieflower", file: "fonts-src/IndieFlower-Regular.ttf" },
  { id: "dancingscript", file: "fonts-src/DancingScript[wght].ttf" },
  { id: "cedarvillecursive", file: "fonts-src/Cedarville-Cursive.ttf" },
  { id: "sacramento", file: "fonts-src/Sacramento-Regular.ttf" },
];

const CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/** 每字形取第一条轮廓上"贴基线、靠左"的点(≈ 连笔书写的入笔处)与初始笔画方向。 */
function guideFor(font, ch) {
  const glyph = font.charToGlyph(ch);
  if (!glyph || glyph.index === 0) return null;
  const cmds = (glyph.path?.commands ?? []).filter((c) => c.type !== "Z");
  if (!cmds.length) return null;
  // 切分成轮廓;轮廓顺序不定(i 的圆点可能在主笔之前),按包围盒面积取主笔画
  const contours = [];
  let cur = [];
  for (const c of cmds) {
    if (c.type === "M" && cur.length) contours.push(cur);
    cur.push(c);
  }
  if (cur.length) contours.push(cur);
  if (!contours.length) return null;
  const ptsOf = (cs) =>
    cs.flatMap((c) =>
      c.type === "C"
        ? [
            { x: c.x1, y: c.y1 },
            { x: c.x2, y: c.y2 },
            { x: c.x, y: c.y },
          ]
        : c.type === "Q"
          ? [
              { x: c.x1, y: c.y1 },
              { x: c.x, y: c.y },
            ]
          : [{ x: c.x, y: c.y }],
    );
  const areaOf = (cs) => {
    const ps = ptsOf(cs);
    const xs = ps.map((p) => p.x);
    const ys = ps.map((p) => p.y);
    return (Math.max(...xs) - Math.min(...xs)) * (Math.max(...ys) - Math.min(...ys));
  };
  const pts = ptsOf(contours.reduce((a, b) => (areaOf(b) > areaOf(a) ? b : a)));
  if (!pts.length) return null;
  const minX = Math.min(...pts.map((p) => p.x));
  const upm = font.unitsPerEm;
  // 连笔书写里每个字母都从基线左侧入笔、向右上走笔:在"贴基线且靠左"的点里
  // 找切线向右上最陡的作为入笔点与方向(切线用中心差分,闭合轮廓回绕安全)。
  const at = (i) => pts[((i % pts.length) + pts.length) % pts.length];
  const far = (i, dir, ref) => {
    for (let s = 1; s < pts.length; s++) {
      const p = at(i + s * dir);
      if (Math.abs(p.x - ref.x) + Math.abs(p.y - ref.y) > 1) return p;
    }
    return null;
  };
  let bestP = null;
  let bestD = null;
  let bestScore = -Infinity;
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i];
    if (Math.abs(p.y) > 0.12 * upm || p.x - minX > 0.45 * upm) continue;
    const pf = far(i, 1, p);
    const pb = far(i, -1, p);
    if (!pf || !pb) continue;
    let dx = pf.x - pb.x;
    let dy = pf.y - pb.y;
    if (Math.abs(dx) + Math.abs(dy) < 1) continue;
    if (dx < 0) {
      dx = -dx;
      dy = -dy;
    }
    if (dy < -0.25 * Math.abs(dx)) continue; // 下行段不是入笔
    const score = dy / (Math.abs(dx) + 1e-6) - (0.3 * (p.x - minX)) / upm;
    if (score > bestScore) {
      bestScore = score;
      bestP = p;
      bestD = { dx, dy };
    }
  }
  if (!bestP) {
    // 兜底:贴基线最左点,方向水平向右
    bestP = pts.reduce((a, b) =>
      Math.abs(b.y) + 0.3 * (b.x - minX) < Math.abs(a.y) + 0.3 * (a.x - minX) ? b : a,
    );
    bestD = { dx: 12, dy: 5 };
  }
  const deg = Math.round((Math.atan2(bestD.dy, bestD.dx) * 180) / Math.PI * 10) / 10;
  return [Math.round(bestP.x), Math.round(bestP.y), deg];
}

const out = {};
for (const f of FONTS) {
  const buffer = fs.readFileSync(path.join(root, f.file));
  const font = opentype.parse(buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength));
  const glyphs = {};
  for (const ch of CHARS) {
    const g = guideFor(font, ch);
    if (g) glyphs[ch] = g;
  }
  const missing = CHARS.split("").filter((ch) => !glyphs[ch]);
  if (missing.length) console.warn(`${f.id}: no outline for ${missing.join("")}`);
  out[f.id] = { upm: font.unitsPerEm, glyphs };
  console.log(`${f.id}: ${Object.keys(glyphs).length} glyphs, upm=${font.unitsPerEm}`);
}

const ts = `// AUTO-GENERATED by scripts/glyph-starts.mjs — do not edit.
// 每字形: [落笔点 x, 落笔点 y, 初始笔画方向角 deg](字体单位,y 向上;canvas 需翻转 y 与角度符号)
export type GlyphGuide = [number, number, number];

export const GLYPH_STARTS: Record<string, { upm: number; glyphs: Record<string, GlyphGuide> }> = ${JSON.stringify(out, null, 0)};
`;

fs.writeFileSync(path.join(root, "src/lib/glyphStarts.generated.ts"), ts);
console.log("written src/lib/glyphStarts.generated.ts");
